packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  # Dev tooling
  eslint: ^9.35.0
  prettier: ^3.6.2
  tailwindcss: ^4.1.17
  typescript: ^5.9.2

  # Misc
  zod: ^4.1.8
  "@t3-oss/env-nextjs": ^0.13.8
  ai: ^5.0.44

  # Tanstack & oRPC
  "@tanstack/react-query": ^5.83.0
  "@orpc/client": ^1.11.3
  "@orpc/openapi": ^1.11.3
  "@orpc/react-query": ^1.11.3
  "@orpc/server": ^1.11.3
  "@orpc/shared": ^1.11.3
  "@orpc/zod": ^1.11.3

  vitest: ^3.2.4

catalogs:
  react19:
    react: 19.2.0
    react-dom: 19.2.0
    "@types/react": ^19.2.6
    "@types/react-dom": ^19.2.3
